coverage:
  range: "80...100"
    
  status:
    project:
      default: off
      unit:
          target: 80%
          flags: unit
      functional:
          target: 90%
          flags: functional
    patch: off
